Repository SUSE/scf, pull requests merged in 2019-09, with the labels that each got.

#2705 jsc#CAP-554: Allow default stemcell to be configured
  deploy/helm/scf/assets/operations/set_opensuse_stemcells.yaml
  deploy/helm/scf/templates/implicit_vars.yaml
  deploy/helm/scf/values.yaml
Labels: v3

#2707 v3 - Eirini support
  WORKSPACE
  bosh/releases/pre_render_scripts/bits/bits-service/jobs/patch_bits_config_yml.sh
  bosh/releases/pre_render_scripts/eirini/eirini-loggregator-bridge/bpm/patch_bpm.sh
  bosh/releases/pre_render_scripts/eirini/opi/bpm/patch_bpm.sh
  bosh/releases/pre_render_scripts/eirini/opi/jobs/patch_opi_yml.sh
  def.bzl
  deploy/helm/scf/assets/operations/certs.yaml
  deploy/helm/scf/assets/operations/instance_groups/api.yaml
  deploy/helm/scf/assets/operations/instance_groups/bits-service.yaml
  deploy/helm/scf/assets/operations/instance_groups/eirini.yaml
  deploy/helm/scf/assets/operations/zz-remove-diego-if-eirini.yaml
  deploy/helm/scf/templates/bosh_deployment.yaml
  deploy/helm/scf/templates/eirini.yaml
  deploy/helm/scf/templates/implicit_vars.yaml
  deploy/helm/scf/templates/ops-use-bits-service.yaml
  deploy/helm/scf/templates/ops.yaml
  deploy/helm/scf/templates/single_availability.yaml
  deploy/helm/scf/values.yaml
  dev/kind/def.bzl
  dev/kind/start.sh
Labels: v3

#2712 v3 - Add initial Github Actions pipeline for publishing
  .github/workflows/publish.yml
  .github/workflows/publish/build.sh
  .github/workflows/publish/publish.sh
  .github/workflows/publish/rename.sh
  .github/workflows/publish/verify.sh
Labels: v3

#2714 Fixed verify step on v3 publish pipeline
  .github/workflows/publish/verify.sh
  .gitignore
Labels: v3

#2721 jsc#CAP-554: Allow default stemcell to be configured
  deploy/helm/scf/assets/operations/set_opensuse_stemcells.yaml
  deploy/helm/scf/templates/implicit_vars.yaml
  deploy/helm/scf/values.yaml
Labels: v3

#2740 v3 - Added temporary cf_cli.sh for creating cf-cli pod
  dev/cf_cli/README.md
  dev/cf_cli/cf_cli.sh
Labels: v3

#2708 v3 - Added ingress
  deploy/helm/scf/templates/ingress.yaml
  deploy/helm/scf/values.yaml
  dev/scf/README.md
  dev/scf/docs/accessing.md
  dev/scf/docs/installing.md
  dev/scf/values.yaml
Labels: v3

#2730 v3 - Switched from Eirini to Diego as default
  deploy/helm/scf/values.yaml
Labels: v3

#2734 v3 - Bumped Kubernetes version to 1.14.6
  def.bzl
Labels: v3

#2736 v3 - Cleaned up implicit vars
  deploy/helm/scf/assets/operations/certs.yaml
  deploy/helm/scf/assets/operations/instance_groups/adapter.yaml
  deploy/helm/scf/assets/operations/instance_groups/api.yaml
  deploy/helm/scf/assets/operations/instance_groups/bits.yaml
  deploy/helm/scf/assets/operations/instance_groups/cc-worker.yaml
  deploy/helm/scf/assets/operations/instance_groups/database.yaml
  deploy/helm/scf/assets/operations/instance_groups/diego-api.yaml
  deploy/helm/scf/assets/operations/instance_groups/diego-cell.yaml
  deploy/helm/scf/assets/operations/instance_groups/doppler.yaml
  deploy/helm/scf/assets/operations/instance_groups/eirini.yaml
  deploy/helm/scf/assets/operations/instance_groups/log-api.yaml
  deploy/helm/scf/assets/operations/instance_groups/router.yaml
  deploy/helm/scf/assets/operations/instance_groups/scheduler.yaml
  deploy/helm/scf/assets/operations/instance_groups/singleton-blobstore.yaml
  deploy/helm/scf/assets/operations/instance_groups/uaa.yaml
  deploy/helm/scf/assets/operations/set_opensuse_stemcells.yaml
  deploy/helm/scf/assets/operations/set_release_urls.yaml
  deploy/helm/scf/templates/implicit_vars.yaml
Labels: v3

#2742 v3 - Fixed regex on cf-cli script
  dev/cf_cli/cf_cli.sh
Labels: v3

#2735 v3 - Removed privileged for rep
  deploy/helm/scf/assets/operations/instance_groups/diego-cell.yaml
Labels: v3

#2746 v3 - Updated Minikube drivers documentation
  dev/minikube/README.md
Labels: v3

#2747 v3 - Added a notice on Minikube updating the default config
  dev/minikube/README.md
Labels: v3

#2761 v3 - Bumped to 16GB the default memory for Minikube
  dev/minikube/def.bzl
Labels: v3

#2807 v3 - Shellcheck managed by Bazel
  WORKSPACE
  def.bzl
  dev/linters/shellcheck.sh
  rules/external_binary/BUILD.bazel
  rules/external_binary/def.bzl
Labels: v3 ✨

#2792 v3 - Added set_suse_buildpacks ops-file
  deploy/helm/scf/assets/operations/buildpacks/set_suse_buildpacks.yaml
  deploy/helm/scf/templates/bosh_deployment.yaml
  deploy/helm/scf/templates/ops.yaml
  deploy/helm/scf/values.yaml
Labels: v3 ✨

#2819 v3 - Allowed custom ops-files to be referenced as configmaps
  deploy/helm/scf/templates/bosh_deployment.yaml
  deploy/helm/scf/values.yaml
Labels: suse tracked, v3 ✨

#2812 V3 bosh author docs
  dev/scf/docs/bosh-author.md
Labels: v3 ✨

#2820 Gitlab CI
  .github/workflows/publish.yml
  .github/workflows/publish/build.sh
  .github/workflows/publish/publish.sh
  .github/workflows/publish/verify.sh
  .gitlab-ci.yml
  .gitlab/deploy/runner/kubernetes/BUILD.bazel
  .gitlab/deploy/runner/kubernetes/README.md
  .gitlab/deploy/runner/kubernetes/deploy.sh
  .gitlab/deploy/runner/kubernetes/values.yaml
  .gitlab/pipelines/stages/build.sh
  .gitlab/pipelines/stages/publish.sh
Labels: CI 🏭, suse tracked, v3 ✨

#2837 v3 - Re-enabled the tee_output_to_sys_log script on ccng
  bosh/releases/pre_render_scripts/api/cloud_controller_ng/jobs/remove_tee_output_to_sys_log.sh
Labels: bug 🐛, v3 ✨
