Repository SUSE/scf, pull requests merged in 2019-10, with the labels that each got.

#2809 Add liveness & readiness probes
  deploy/helm/scf/assets/operations/instance_groups/adapter.yaml
  deploy/helm/scf/assets/operations/instance_groups/api.yaml
  deploy/helm/scf/assets/operations/instance_groups/cc-worker.yaml
  deploy/helm/scf/assets/operations/instance_groups/database.yaml
  deploy/helm/scf/assets/operations/instance_groups/diego-api.yaml
  deploy/helm/scf/assets/operations/instance_groups/diego-cell.yaml
  deploy/helm/scf/assets/operations/instance_groups/doppler.yaml
  deploy/helm/scf/assets/operations/instance_groups/log-api.yaml
  deploy/helm/scf/assets/operations/instance_groups/nats.yaml
  deploy/helm/scf/assets/operations/instance_groups/router.yaml
  deploy/helm/scf/assets/operations/instance_groups/scheduler.yaml
  deploy/helm/scf/assets/operations/instance_groups/singleton-blobstore.yaml
  deploy/helm/scf/assets/operations/instance_groups/uaa.yaml
Labels: suse tracked, v3 ✨

#2887 v3 - Fixed publish step with Gitlab CI
  .gitlab-ci.yml
  .gitlab/pipelines/stages/publish.sh
Labels: CI 🏭, v3 ✨

#2787 Initial commit of acceptance tests
  deploy/helm/scf/assets/operations/instance_groups/acceptance-tests.yaml
  deploy/helm/scf/assets/operations/temporary/cf-acceptance-tests-stemcell.yaml
  deploy/helm/scf/templates/bosh_deployment.yaml
  deploy/helm/scf/templates/ops.yaml
  testing/README.md
  testing/acceptance_tests/BUILD.bazel
  testing/acceptance_tests/README.md
  testing/acceptance_tests/trigger.yaml
Labels: suse tracked, v3 ✨

#2876 Add install instructions for the helm release
  INSTALL.md
Labels: v3 ✨

#2942 Set INSTANCE_ID to reference pod-ordinal label
  deploy/helm/scf/assets/operations/instance_groups/doppler.yaml
  deploy/helm/scf/assets/operations/instance_groups/scheduler.yaml
Labels: bug 🐛, v3 ✨

#2845 Make patch for eirini-loggregator-bridge bpm idempotent
  bosh/releases/pre_render_scripts/eirini/eirini-loggregator-bridge/bpm/patch_bpm.sh
Labels: v3 ✨

#2968 Add permalink to the fissile command
  dev/scf/docs/bosh-author.md
Labels: v3 ✨

#2916 Switched from k8s headless svc DNS resolution to BOSH aliases
  bosh/releases/pre_render_scripts/singleton-blobstore/blobstore/ig_resolver/patch_job_mf.sh
  bosh/releases/pre_render_scripts/singleton-blobstore/blobstore/jobs/patch_blobstore_conf.sh
  deploy/helm/scf/assets/operations/addons.yaml
  deploy/helm/scf/assets/operations/certs.yaml
  deploy/helm/scf/assets/operations/instance_groups/adapter.yaml
  deploy/helm/scf/assets/operations/instance_groups/api.yaml
  deploy/helm/scf/assets/operations/instance_groups/bits.yaml
  deploy/helm/scf/assets/operations/instance_groups/cc-worker.yaml
  deploy/helm/scf/assets/operations/instance_groups/database.yaml
  deploy/helm/scf/assets/operations/instance_groups/diego-api.yaml
  deploy/helm/scf/assets/operations/instance_groups/diego-cell.yaml
  deploy/helm/scf/assets/operations/instance_groups/doppler.yaml
  deploy/helm/scf/assets/operations/instance_groups/eirini.yaml
  deploy/helm/scf/assets/operations/instance_groups/log-api.yaml
  deploy/helm/scf/assets/operations/instance_groups/nats.yaml
  deploy/helm/scf/assets/operations/instance_groups/router.yaml
  deploy/helm/scf/assets/operations/instance_groups/scheduler.yaml
  deploy/helm/scf/assets/operations/instance_groups/singleton-blobstore.yaml
  deploy/helm/scf/assets/operations/instance_groups/uaa.yaml
  deploy/helm/scf/assets/operations/temporary/remove_variables.yaml
Labels: spike 🐱‍🏍, v3 ✨
